-- Dropa as tabelas usando DROP TABLE ... CASCADE
DROP TABLE IF EXISTS "perguntas" CASCADE;
DROP TABLE IF EXISTS "avaliacoes" CASCADE;
DROP TABLE IF EXISTS "fotos_produto" CASCADE;
DROP TABLE IF EXISTS "compras" CASCADE;
DROP TABLE IF EXISTS "documentos" CASCADE;
DROP TABLE IF EXISTS "enderecos" CASCADE;
DROP TABLE IF EXISTS "usuarios" CASCADE;
DROP TABLE IF EXISTS "tipos_usuarios" CASCADE;
DROP TABLE IF EXISTS "tipos_documentos" CASCADE;
DROP TABLE IF EXISTS "tipos_produtos" CASCADE;
DROP TABLE IF EXISTS "estados_conservacao" CASCADE;
DROP TABLE IF EXISTS "anuncios" CASCADE;
DROP TABLE IF EXISTS "produtos" CASCADE;
DROP TABLE IF EXISTS "status_compra" CASCADE;
DROP TABLE IF EXISTS "endereco_compra" CASCADE;